### ISSUE TITLE
vllm-inference-openai.service is not active after terraform install 

### ISSUE THREAD

**Issue by aviv12825** [oracle-devrel/oci-terraform-genai-llm-on-gpuvms#3]
[opc@gpuA10llmhost ~]$  sudo systemctl status vllm-inference-openai.service
vllm-inference-openai.service - systemd service start vllm-inference-openai.service
Loaded: loaded (/etc/systemd/system/vllm-inference-openai.service; enabled; vendor preset: disabled)
Active: activating (auto-restart) (Result: exit-code) since Thu 2024-05-16 13:37:25 GMT; 1s ago
Process: 66075 ExecStart=/usr/bin/bash bash_openai.sh (code=exited, status=1/FAILURE)
Main PID: 66075 (code=exited, status=1/FAILURE)

**Comment by RahulMR42** [comment]
thank you ,added #4
